[phases.setup]
nixPkgs = [
    "nodePackages.npm", 
    "nodejs-20_x",
    "chromium",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "cups",
    "libdrm",
    "libxkbcommon",
    "pango",
    "cairo",
    "mesa"
]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"
