[phases.setup]
nixPkgs = [
    "nodePackages.npm", 
    "nodejs-20_x",
    "chromium",
    "glib",
    "nss",
    "nspr",
    "atk",
    "at-spi2-atk",
    "at-spi2-core",
    "cups",
    "dbus",
    "libdrm",
    "libxkbcommon",
    "pango",
    "cairo",
    "mesa",
    "expat",
    "libxcb",
    "alsa-lib",
    "gtk3"
]

[phases.build]
cmds = ["npm install"]

[phases.start]
cmd = "node server.js"
